language:  java
env:
  -DB=mysql
jdk: openjdk11
services:
  - mysql
before_install:
  - mysql -u root --password=""
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gupb;'
branches:
  only:
    - main
    - /feature\/.+/